# Generated by Django 3.2 on 2021-04-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('api_type', models.CharField(choices=[('test', 'test'), ('production', 'production')], max_length=11)),
                ('api_uri', models.URLField(blank=True, null=True, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('secret_key', models.CharField(blank=True, max_length=36, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('trial_period', models.PositiveIntegerField(default=15)),
                ('limits', models.PositiveIntegerField(default=30)),
                ('auto_renewal', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(blank=True, choices=[(0, 'admin'), (1, 'developer'), (2, 'user')], null=True)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application_env_variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_Key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('value', models.CharField(max_length=155)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Application_D_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mysql', 'mysql'), ('postgre', 'postgre'), ('sqlserver', 'sqlserver')], max_length=9)),
                ('host', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('port_number', models.IntegerField()),
                ('dbname', models.CharField(blank=True, choices=[('mysql', 'mysql'), ('postgre', 'postgre'), ('sqlserver', 'sqlserver')], max_length=9, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Application_custom_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
                ('code', models.TextField()),
                ('frequency', models.IntegerField(default=1)),
                ('interval', models.IntegerField(default=0)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Application_custom_mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.TextField()),
                ('frequency', models.IntegerField(default=1)),
                ('interval', models.IntegerField(default=0)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.subscription'),
        ),
    ]
